.logo-header-inner{text-align:left;}.logo-header-inner{text-align:left;display:inline-block;}.site-navigation-inner{text-align:center;}a,.page-header h2.page-title a:hover,.post-overlay .post-readmore a:hover,
    .latest-carousel-content-in .content-in >div a:hover,ul.main-menu li ul li a:hover,.nav>li>a:hover, 
    .nav>li>a:focus,.themewing_instagram_widget p.clearfix a:hover, 
    .post-single-wrap .meta-category a:hover,
    .post-overlay .meta-category a:hover,.featured-post-item-inner h4 a:hover,
    .footer-social-buttons ul li i,.footer-social-buttons ul li a:hover,#back-to-top .btn.btn-primary:hover,
    .paging-navigation .post-nav  li>span,#nav-below.post-navigation ul li a:hover,
    .post-related h4 a:hover,sup.featured-post,.widget ul.nav>li>a:hover,
    .entry-blog:hover .readmore-blog,.off-canvas-list li a:hover,.header-social-buttons ul li a:hover,
    .cd-slider-nav.main-slide-control ul li.selected a,
.cd-slider-nav.main-slide-control ul li:hover a, .cd-slider-nav.main-slide-control ul li a,
ul.main-menu li ul li.current-menu-item a,
.widget .widget_title,.blog-header h2.page-title a:hover,.slider-layout3-btn a:hover,
.latest-post-content h4 a:hover,.latest-post-content2 h4 a:hover,
.slider-layout2-item .owl-theme .owl-controls .owl-next:hover:after,
.slider-layout3-item .owl-theme .owl-controls .owl-next:hover:after,
.slider-layout2-item .owl-theme .owl-controls .owl-prev:hover:after,
.slider-layout3-item .owl-theme .owl-controls .owl-prev:hover:after,
.slider-layout3-item-inner .meta-category a:hover,
.nav>li.current-menu-item>a,.meta-tag a:hover,blockquote p:before { color:#1e73be; }.paging-navigation .post-nav li>a:hover, 
    .paging-navigation .post-nav li>a:focus{ color: #1e73be!important; }#back-to-top .btn.btn-primary,.post-single-wrap .meta-category a,
    .themewing-about-social li a:hover,.owl-theme .owl-dots .owl-dot.active span,.post-overlay .meta-category a, 
.owl-theme .owl-dots .owl-dot:hover span,.latest-course-control a:hover,.site-search,
.form-submit .btn.btn-primary,.widget.widget_tag_cloud .tagcloud a:hover,.wpcf7-form-control.wpcf7-submit,
.top-menu li a:after,.display-header #header-trigger .icon-bar,
#header-trigger:hover .icon-bar,.thw-offcanvas .nano > .nano-pane > .nano-slider,
.header-social-buttons-list ul,.meta-category-inner:before,.meta-category-inner:after,
.meta-category-inner a,#featured-post .item:hover .overlay,.feature-cats a,
.blogon-newsltter input[type=submit],.copyright-info:after,
.navbar-header .navbar-toggle:hover .icon-bar,.entry-blog ul li:before,
.header-social-buttons-list,button, input[type=button], input[type=reset], input[type=submit]{ background-color:#1e73be; }.latest-course-control a:hover,.post-single-wrap .meta-category a:hover,
     .paging-navigation .post-nav  li>span,.form-submit .btn.btn-primary,
    .widget.widget_tag_cloud .tagcloud a:hover,.error404 .common-btns,
    button, input[type=button], input[type=reset], input[type=submit],
    .slider-layout3-btn a:hover{ border-color:#1e73be; }.entry-blog:hover .readmore-blog{ border-bottom: 1px solid #1e73be; }a:hover{ color:#10ace5; }.form-submit .btn.btn-primary:hover,
  button:hover, input[type=button]:hover, input[type=reset]:hover, input[type=submit]:hover{ background-color:#10ace5; }.thw-menubar{ background:#ffffff; }#body-inner{ background:#f5f5f5; }